### ISSUE TITLE
Jump to bottom Not showing thumbnail of YouTube feeds in flym app,

### ISSUE THREAD

**Issue by Ramrajaadhikari** [prof18/feed-flow#107]
Not showing thumbnail of YouTube feeds in flym app .

**Comment by prof18** [comment]
Can you share a link of such feeds?

**Comment by Ramrajaadhikari** [comment]
![XRecorder_07012024_225738](https://github.com/prof18/feed-flow/assets/93089438/c176f1ce-2144-48f5-b3b3-46084350e3e7)

**Comment by Ramrajaadhikari** [comment]
The app is showing shot brifing but there is not photo. The link is YouTube link.

**Comment by Ramrajaadhikari** [comment]
All of my YouTube feeds are not supporting thumbnail. The feeds are
In opml form.
