### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by KasimiraEike** [prof18/feed-flow#110]
Do you plan to release [FeedFlow](https://www.feedflow.dev/) on [F-Droid](https://f-droid.org/)?

**Comment by prof18** [comment]
Yes, I'm planning to do soon!

**Comment by shuvashish76** [comment]
Requested at F-Droid: https://gitlab.com/fdroid/rfp/-/issues/2870

**Comment by licaon-kter** [comment]
Fastlane (https://gitlab.com/-/snippets/1895688) ?

Reproducible builds (https://f-droid.org/docs/Inclusion_How-To/#reproducible-builds) ?

Flavor without non-FLOSS Firebase/Crashlytics ?

**Comment by prof18** [comment]
Yes, I have to create a flavor without Crashlytics and probably without the Dropbox sync because I don't know where to save the API key for the FDroid build

**Comment by prof18** [comment]
Update: Merge Request sent to FDroid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15755

**Comment by sette15** [comment]
that's great, thanks! It'd be fantastic if you could also release a FOSS apk version here in github, so whoever is using Obtainium would definitely benefit that. thanks

**Comment by sette15** [comment]
@codenyte oh yea, I know. the only issue is that f-droid releases slowler than the ones on github

**Comment by shuvashish76** [comment]
Live on F-Droid 🎉, feel free to use their badge : https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md

You can close this issue now, ThankYou.

**Comment by prof18** [comment]
Yes, I will update the readme and the website soon

**Comment by chrysle** [comment]
When do we get the newer versions on F-Droid? Can't wait for the new editing feature!

**Comment by prof18** [comment]
Depends on how fast Fdroid is in building the app! Could be up to 7days!

**Comment by Coool** [comment]
> Yes, I have to create a flavor without Crashlytics and probably without the Dropbox sync because I don't know where to save the API key for the FDroid build

What else is different between the Google Play and F-Droid versions?
