### ISSUE TITLE
iOS devices crash on the home page Add Feed

### ISSUE THREAD

**Issue by KangodYan** [prof18/feed-flow#154]
On the homepage, click `Add feed -> Add feed` or `Add feed -> Import and export OPML` will cause the app to crash.

However, if I enter from the `settings -> Add feed` or another, it won't crash.

My device is an iPhone SE3, The iOS version is 16.7.2.

**Comment by prof18** [comment]
Is it crashing before selecting the OPML or after the import process starts? In such a case, would you mind sharing the OPML? Even privately, if you prefer.

**Comment by KangodYan** [comment]
It is crashing before selecting the OPML.
The input pages for 'Add Feed' and 'Import and Export OPML' flashed briefly, and then the app crashed.

**Comment by prof18** [comment]
Fixed by https://github.com/prof18/feed-flow/pull/173, it will be available in the next release.

It seems to be a bug on iOS 16; on iOS 17, it works perfectly. As a workaround, it will open the settings sheet.
