### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by P0bo** [prof18/feed-flow#155]
In an RSS feed reader, a search feature can greatly enhance user experience and efficiency by allowing users to quickly find specific articles or topics of interest. Here's why:

- **Efficient Content Discovery:** With the vast amount of content available in RSS feeds, a search feature enables users to easily locate specific articles or topics without manually browsing through numerous feeds.

- **Time-Saving:** Instead of scrolling through a long list of articles (i get over 500 articles update a day ) , users can simply enter their search query and retrieve relevant results instantly, saving time and effort.

Also a advanced search feature will be really cool to further pinpoint specific article 

## Advanced Search Functionality for RSS Feed Reader

- **Advanced Operators:** Users can utilize operators like | (OR), - (NOT), and " (quotes) for more precise searches. For instance, combining search terms with | allows matching any of the words, while prefixing with - excludes results matching a certain word.

- **Phrase Searching:** To search for a several-word expression in its entirety, users can enclose searches with " (double quotes), ensuring accurate results.

### Search Examples for RSS Feed Reader

1. **Filtering and Excluding:**
   - Search for articles about "Science Fiction" but exclude any mentioning "Fantasy":
     ```
     "Science Fiction" -Fantasy
     ```

2. **Phrase Searching and Grouping:**
   - Find articles discussing either "Artificial Intelligence" or "Machine Learning":
     ```
     "Artificial Intelligence"|"Machine Learning"
     ```

3. **Combining Operators:**
   - Look for articles related to "Space Exploration" with mentions of "Mars":
     ```
     "Space Exploration" Mars
     ```

These examples illustrate how users can refine their searches using advanced operators, ensuring more precise and tailored results.

**Comment by Luffyirl** [comment]
Advanced search would be cool tho .  l'd really love it and ofc use it as the feeds i have gives articles  really similar name if i could specify in this way there will be less clutter.
