### ISSUE TITLE
Ability to change feed names .

### ISSUE THREAD

**Issue by Luffyirl** [prof18/feed-flow#166]
Ability to change feed names will help maintain clean and minimal look and give a better way to navigate betwwen feeds with similar names. 
![Screenshot_2024-03-30-15-37-25-43_ec2eb6fa460e4a1f71f8b51a239fd3fc](https://github.com/prof18/feed-flow/assets/128812994/382a927d-d93e-4b7d-be9f-1cc28da789cd)

**Comment by prof18** [comment]
Done in https://github.com/prof18/feed-flow/pull/170, it will be available on the next release
