### ISSUE TITLE
hide description or title  for Certain feeds / use desciption as title 

### ISSUE THREAD

**Issue by Luffyirl** [prof18/feed-flow#172]
Some feeds provide the title in `title`  and  actal title +extra info in `description` or the website name in `title` and the article title in `description` or article number in `title` and article  title in  `description` . it would be great if there was an option to only show title or only show description or show both for feeds individually .currently feed flow shows both .

**Comment by prof18** [comment]
Closing, because I'm keeping #186 as a reference for the issue
