### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by drtn222** [prof18/feed-flow#257]
Love the app, thanks for your efforts. I'd like to see some more options, but the most pressiong, which almost makes it a dealbraker for me is the text size. It is too small, both in article list and especially in reader mode. Ability to change font size would be great. Thanks!

**Comment by prof18** [comment]
Thanks for reporting it! 
I've already planned such a feature, it will come in a future release.

**Comment by prof18** [comment]
The ability to change font size on the reader mode will be available on the next release! 
#305
