### ISSUE TITLE
Link Invalid For Local RSS Feed

### ISSUE THREAD

**Issue by CamarataM** [prof18/feed-flow#312]
Hello.

Using FeedFlow, I attempted to add an RSS feed which is published on my local network at the URL 'http://192.168.0.123:12345/ludum-dare.rss' while connected to my local network. However, this is not recognized as a valid feed using FeedFlow, showing the error "The link you provided is not a valid RSS feed". Using RSS Parser and a test Android app, I was able to get the RSS channel from this URL without issue (after having to add the android:usesCleartextTraffic attribute, but it seems like FeedFlow already has that added).

I have attached the one of the RSS feeds below, although it happened to all three of my local RSS feeds. Running the RSS feed through W3C's feed validator, it shows having issues with the GUID having an em-dash (removing these didn't seem to fix this) and the feed missing a atom:link element (adding this did not seem to fix this), but this RSS feed parses fine both using RSS Parser and Feeder, so I'm not sure what the problem is.

[ludum-dare.zip](https://github.com/user-attachments/files/17138256/ludum-dare.zip)

It seems like FeedFlow is making a bunch of invalid HTTP requests judging from the log when hosting the file through Python's http.server. I have attached a log from that as well.

[http-server-log.txt](https://github.com/user-attachments/files/17138304/http-server-log.txt)

**Comment by prof18** [comment]
Interesting! On paper, it should work with local feeds. I'll try to host your feed and see if I can debug the issue!

**Comment by CamarataM** [comment]
Alright, I found the issue. When adding the feed, the call to 'sanitizeUrl(feedUrl)' in 'AddFeedViewModel' replaces 'http' with 'https', which isn't valid if the server only supports 'http'. Removing 'sanitizeUrl' allows the feed to be added once the URL is prefixed with 'http' (just '192.168.0.123...' won't work). Since 'http' is always replaced with 'https', there is no way to add the URL currently even if the URL has 'http' at the beginning.

**Comment by prof18** [comment]
ah right! I'll fix it soon then
