### ISSUE TITLE
Cannot change categories after adding feed on Android

### ISSUE THREAD

**Issue by aquacash5** [prof18/feed-flow#321]
After adding a feed, there does not seem to be a way to add that feed to a category (or remove a feed from a category).

**Comment by prof18** [comment]
Correct, for now, you can only do it on creation. 
Thank you for the suggestion, I will put it in the roadmap.

**Comment by prof18** [comment]
Fixed in https://github.com/prof18/feed-flow/pull/353, will be available on the next release.
