### ISSUE TITLE
Selecting settings from within a feed takes users to application wide settings

### ISSUE THREAD

**Issue by aquacash5** [prof18/feed-flow#322]
On Android, selecting the settings menu item from the `⋮` menu always takes you to the app settings. Even when you have selected a specific feed.

I expected that if I selected a specific feed, the settings menu item would take me to the feeds settings. Where I can update the URL, Categories, Polling rate, etc...

**Comment by prof18** [comment]
I haven't thought about that, but it makes sense! Thank you for the suggestion, I will put in the roadmap.

**Comment by aquacash5** [comment]
Alternate suggestion, when you have a feed selected, add a `Edit Feed` option to the menu.

**Comment by prof18** [comment]
Fixed in https://github.com/prof18/feed-flow/pull/358, it will be available on the next release
