### ISSUE TITLE
Another Invalid Feed

### ISSUE THREAD

**Issue by commonsguy** [prof18/feed-flow#333]
https://scottpierce.dev/posts/index.xml is valid according to [the W3C validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fscottpierce.dev%2Fposts%2Findex.xml), but FeedFlow 1.0.76 reports it as invalid.

Let me know if you need more information, and thanks for writing this app!

**Comment by prof18** [comment]
Thank you!

I don't know what I did, but from `1.0.77` it works 😅

**Comment by commonsguy** [comment]
Agreed! And my apologies for missing the 1.0.77 update!

**Comment by prof18** [comment]
No worries :D
