### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [prof18/feed-flow#335]
https://github.com/prof18/feed-flow/blob/663c62d68c1d61045d82bbd52945af3d0a2b28d6/shared/build.gradle.kts#L111 It seems this lib is used in fdroid flavor. Could you please take a look? Thanks!

**Comment by prof18** [comment]
Ah, right!  It was a leftover from the cleanup. I'll trigger a new release soon. 

(even tho the library was included, nothing was actually called -  see https://github.com/prof18/feed-flow/blob/main/androidApp/src/fdroid/kotlin/com/prof18/feedflow/android/CrashlyticsHelper.kt)

**Comment by prof18** [comment]
@linsui shall I leave the existing tag and create a new one or delete the old one and re-create it?

**Comment by linsui** [comment]
Both work. :)

**Comment by prof18** [comment]
I've just deleted and recreated `0.0.59-fdroid` :) Thanks!

**Comment by linsui** [comment]
Thanks!
