### ISSUE TITLE
Quick Access to Feed Settings via Long Press

### ISSUE THREAD

**Issue by marcellogalhardo** [prof18/feed-flow#349]
In the drawer menu, under Feed Source, a long press on a source could directly open its feed settings.

Currently, accessing feed settings requires opening the feed, tapping the three dots, and selecting settings.

Alternatively, a long press could open the same modal that appears when tapping the three dots after opening a feed.

**Comment by prof18** [comment]
Yes, it's something I need to improve, thank you for the suggestion!

Something similar was also reported on https://github.com/prof18/feed-flow/issues/322

**Comment by prof18** [comment]
Fixed by https://github.com/prof18/feed-flow/pull/361, it will be available on the next release
