### ISSUE TITLE
some rss links are not valid

### ISSUE THREAD

**Issue by evoke322** [prof18/feed-flow#42]
for example http://jandan.net/rss and https://www.gatesnotes.com/rss, but they're working in other rss reader. Android app ver0.0.34

**Comment by P0bo** [comment]
https://raw.githubusercontent.com/P0bo/Anime-Tosho/main/rssfeed/airing.xml  i also have the same issue with this feed and 5 other feeds in the same directory but all of them are working on other rss clients

**Comment by prof18** [comment]
`http://jandan.net/rss` still is failing, I'll need to investigate more, but the other are working now. The fix will be available in the next release
