### ISSUE TITLE
Intergrate with Omnivore

### ISSUE THREAD

**Issue by shawn1thompson** [prof18/feed-flow#74]
As the title says. Thank you.

**Comment by prof18** [comment]
Thanks for the suggestion, noted!

Do you mean the integration with the rss feeds on omnivore or to add the link on omnivore?

**Comment by shawn1thompson** [comment]
@prof18 I meant the latter.

**Comment by prof18** [comment]
Thanks for clarifying! I will think about it!

**Comment by prof18** [comment]
Closing this because Omnivore is shutting down :(
