### ISSUE TITLE
Mark individual feed as read

### ISSUE THREAD

**Issue by shawn1thompson** [prof18/feed-flow#84]
Maybe I'm not seeing the way to do this, but I would like to be able to mark individual feeds as read. This is helpful when moving from another reader as an example. I also don't see a way to mark individual posts as read, so maybe this is by design.

**Comment by prof18** [comment]
Good point noted! 
Now, the articles are marked as read as soon as the article leaves the screen. Or you can mark everything as read. 
I'll think about adding it in future relases
