### ISSUE TITLE
Posts disappearing 

### ISSUE THREAD

**Issue by marcellogalhardo** [prof18/feed-flow#90]
Once I add a new RSS reader, and reload the app - the articles appears as expected. That seems correct. The next time I open the app after closing - the feed is empty. That is very confusing, and I don't really know how to access the previous posts.

As a suggestion, articles should never disappear without the user directly archiving it.

| Before Feed | With Feed | Next Launch |
|---|---|---|
| ![Screenshot_20231226-151152](https://github.com/prof18/feed-flow/assets/4348197/91c64d11-ba74-4b14-88a9-6238076496b9) | ![Screenshot_20231226-151221](https://github.com/prof18/feed-flow/assets/4348197/3b3a4d81-bdc4-4d67-b468-e760a2852805) | ![Screenshot_20231226-151232](https://github.com/prof18/feed-flow/assets/4348197/fd4f832b-6f7f-4394-9e71-b99b7471ca9a)

**Comment by prof18** [comment]
It happens because when you reach the end of the list, it automatically sets everything as read. 

But I agree that it is super confusing, I'll revert the change back :D 
Thanks for reporting 🙏

**Comment by prof18** [comment]
Just to clarify, right now, a post is marked as read when opening it and when it's scrolled up outside of the viewport!

(Yes, I'll have to add an onboarding or a guide of the app 😁 )

**Comment by marcellogalhardo** [comment]
Hey @prof18, thanks for the quick reply!

In my opinion, FeedFlow should:

- Only a post that has been clicked should be considered read.
- Scrolls should not mark posts as read. Someone may miss an interesting post due to scrolling to read another post, and the post disappears as read.
- You may want to add an action to "mark as read" and "mark as unread" that can be applied individually.
- There should be a way to see all the unread posts (filtered).
- I would consider adding a Settings that let users filter out or not read articles. I personally prefer to see them.

Please, keep in mind that those are my opinions but I don't want to push anything. Thanks for maintaining the app!

**Comment by prof18** [comment]
That's the kind of feedback I'm looking for! Thank you very much, I'll note them in my roadmap.

btw, I'm also thinking of adding a setting to choose between marking an article when scrolling or not
