### ISSUE TITLE
Add Feed button doesn't open add Feed screen 

### ISSUE THREAD

**Issue by marcellogalhardo** [prof18/feed-flow#91]
Pressing "Add Feed" currently opens the Settings screen instead of the Add New Feed screen, requiring two additional taps. It would be more efficient to directly open the Add Feed screen.

![Screenshot_20231226-151152](https://github.com/prof18/feed-flow/assets/4348197/c32758cf-deea-4d0b-98eb-9937f025e729)

**Comment by prof18** [comment]
Thanks for the suggestion! 

It opens the settings to give also the possibility to import a feed through OPML. But I agree. I will think about adding a popup/bottom sheet to quickly choose between add feed and import OPML!
