### ISSUE TITLE
Do not group Uncategorized if no categories exists

### ISSUE THREAD

**Issue by marcellogalhardo** [prof18/feed-flow#92]
When no categories exist, all items go into a collapsible "Uncategorized" section. If you don't want to categorize your feeds, it requires two taps to check the feed each time.

I recommend showing feeds without a collapsible section if the user doesn't create categories. Alternatively, automatically expand the "Uncategorized" section when no other sections exist.

![Screenshot_20231226-152456](https://github.com/prof18/feed-flow/assets/4348197/4d0409ea-3ec0-43ca-b6c3-aa99a62accb1)
![Screenshot_20231226-152506](https://github.com/prof18/feed-flow/assets/4348197/2e6317c2-85c5-46af-b94c-97cf3b26c9df)

**Comment by prof18** [comment]
Good point, thanks! Noted.
