### ISSUE TITLE
No way to refresh the feed after adding the first RSS feed

### ISSUE THREAD

**Issue by marcellogalhardo** [prof18/feed-flow#93]
Open the app after clean install, add a new feed. Go back to the home screen. The app correctly shows the count of posts but is empty, and pull to refresh doesn't work. The only way to refresh, seems to close and reopen the app.

![Screenshot_20231226-152832](https://github.com/prof18/feed-flow/assets/4348197/0738d134-b9b1-40a7-af30-56cf0db7d228)

**Comment by prof18** [comment]
Ups, that was a 🐛 

Thanks, for reporting! 🙏
