### ISSUE TITLE
Feeds are not completely loaded

### ISSUE THREAD

**Issue by marcellogalhardo** [prof18/feed-flow#94]
After adding the feed "https://tonsky.me/atom.xml", only 5 posts were imported from many. Other RSS Readers are importing all of them; not sure if that is an intentional behaviour or not - but if yes, there must be an option on settings for the user to set the preferences.

**Comment by prof18** [comment]
I can only see 5 items in the feed 🤔 
![Uploading Screenshot 2023-12-26 at 20.45.09.png…]()
Probably the other clients have stored the old articles when they were available

**Comment by marcellogalhardo** [comment]
Interesting. If that is the case, there isn't anything to change. Thank you for taking a look.
